name: Deploy Python App to Azure

on:
  push:
    branches:
      - main

# ADD THIS PERMISSIONS BLOCK HERE
permissions:
  id-token: write  # This is required for requesting the JWT OIDC token
  contents: read    # Required to fetch your repository code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyWebAppsuri'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'   # Forces GitHub to package the exact root folder content
          clean: true
